[theme]
primaryColor = "#667eea"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#13132a"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 10000
maxUploadSize = 10
enableWebsocketCompression = true

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[client]
showErrorDetails = false
toolbarMode = "minimal"